/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Category, Nominee } from "./types";

export const CONTACT_INFO = {
  email: "awolamerica@hotmail.com",
  website: "www.awolamerica.org",
  websiteUrl: "https://www.awolamerica.org",
  telephone: "301-379-7049",
  formsAppUrl: "https://qh4dxvvs.forms.app/awol-america-awards-nomination",
  chairman: "Mohamed Majid Kamara",
  title: "Chairman, AWOL AMERICA",
};

export const TIMELINE_DATES = {
  announcement: "July 3, 2026",
  nominationStart: "2026-07-10T00:00:00",
  nominationEnd: "2026-07-30T23:59:59",
  votingStart: "2026-07-31T00:00:00",
  votingEnd: "2026-08-25T23:59:59",
  ceremony: "2026-09-05T18:00:00",
};

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "New Artist of the Year",
    description: "Honoring emerging musical or visual artists who have made a stunning breakthrough impact this year.",
    iconName: "Sparkles",
  },
  {
    id: 2,
    name: "Thriving Local Business",
    description: "Recognizing local enterprises that demonstrate exceptional resilience, community support, and commercial success.",
    iconName: "Briefcase",
  },
  {
    id: 3,
    name: "DJ of the Year",
    description: "Celebrating DJs who excel in performance, musical curation, crowd engagement, and community presence.",
    iconName: "Music",
  },
  {
    id: 4,
    name: "Social Media / Content Creator of the Year",
    description: "Honoring individuals producing highly engaging, positive, and impactful digital media content.",
    iconName: "Video",
  },
  {
    id: 5,
    name: "Alumni of the Year",
    description: "Recognizing outstanding graduates or former members who continue to embody AWOL's core values in their career.",
    iconName: "GraduationCap",
  },
  {
    id: 6,
    name: "Moseray Fadika Humanitarian Award",
    description: "Our signature award celebrating extraordinary selflessness, charitable impact, and lifelong dedication to humanitarian service.",
    iconName: "HeartHandshake",
  },
  {
    id: 7,
    name: "Musician/Artist of the Year",
    description: "Recognizing established musicians or artists whose creative work has achieved widespread national or global acclaim.",
    iconName: "Mic2",
  },
  {
    id: 8,
    name: "Legendary Award",
    description: "A lifetime achievement honor celebrating individuals who have made historic, enduring contributions to their field.",
    iconName: "Trophy",
  },
  {
    id: 9,
    name: "Descendants Union of the Year",
    description: "Celebrating ancestral or regional descendant organizations that foster unity, cultural preservation, and social support.",
    iconName: "Users2",
  },
  {
    id: 10,
    name: "International Act of the Year Award",
    description: "Honoring global icons and international figures whose artistry or positive deeds transcend national boundaries.",
    iconName: "Globe2",
  },
  {
    id: 11,
    name: "Professional Award of the Year",
    description: "Awarded to exceptional working professionals (healthcare, education, law, tech) demonstrating outstanding leadership.",
    iconName: "Award",
  },
];

export const INITIAL_NOMINEES: Nominee[] = [
  // 1. New Artist of the Year
  { id: "nom-1-1", categoryId: 1, name: "Sia Amara", description: "Rising vocalist blending traditional Sierra Leonean folk with modern soul.", votes: 142 },
  { id: "nom-1-2", categoryId: 1, name: "K-Man Junior", description: "Young afrobeat sensation with back-to-back viral hits.", votes: 118 },
  { id: "nom-1-3", categoryId: 1, name: "Fatima Jalloh", description: "Visual artist focusing on West African diaspora identities.", votes: 95 },

  // 2. Thriving Local Business
  { id: "nom-2-1", categoryId: 2, name: "Salone Spice Bistro", description: "Local restaurant chain employing youth and celebrating cultural cuisine.", votes: 204 },
  { id: "nom-2-2", categoryId: 2, name: "Kono Gem Logistics", description: "Pioneering eco-friendly shipping and delivery service.", votes: 188 },
  { id: "nom-2-3", categoryId: 2, name: "Sierra Loom Fabrics", description: "Boutique standardizing traditional country-cloth production.", votes: 167 },

  // 3. DJ of the Year
  { id: "nom-3-1", categoryId: 3, name: "DJ Base", description: "Legendary radio host and champion of local indie artists.", votes: 312 },
  { id: "nom-3-2", categoryId: 3, name: "DJ Flame", description: "Club and festival favorite known for spectacular transitions.", votes: 284 },
  { id: "nom-3-3", categoryId: 3, name: "DJ Sparkz", description: "Pioneering female DJ leading community sound system projects.", votes: 299 },

  // 4. Social Media / Content Creator of the Year
  { id: "nom-4-1", categoryId: 4, name: "Vamboi Comedy", description: "Creating wholesome, cultural skits that bring families together.", votes: 412 },
  { id: "nom-4-2", categoryId: 4, name: "Salone Tech Review", description: "Educating thousands on digital skills and hardware in Krio.", votes: 315 },
  { id: "nom-4-3", categoryId: 4, name: "The Wandering Sierra", description: "High-production travel vlogging showcasing national tourism.", votes: 380 },

  // 5. Alumni of the Year
  { id: "nom-5-1", categoryId: 5, name: "Dr. Lansana Conteh", description: "Class of 2017. Built a non-profit clinic network in regional towns.", votes: 154 },
  { id: "nom-5-2", categoryId: 5, name: "Mariama Turay, Esq.", description: "Class of 2019. Leading human rights attorney advocating for girls.", votes: 189 },
  { id: "nom-5-3", categoryId: 5, name: "Abu Bakarr Kamara", description: "Class of 2015. Tech lead championing STEM education pipelines.", votes: 144 },

  // 6. Moseray Fadika Humanitarian Award
  { id: "nom-6-1", categoryId: 6, name: "The Mercy Foundation", description: "Providing clean drinking water and sanitary installations to over 50 schools.", votes: 532 },
  { id: "nom-6-2", categoryId: 6, name: "Mother Fatima's Orphanage", description: "Providing loving homes, education, and nutrition to vulnerable children for 20 years.", votes: 611 },
  { id: "nom-6-3", categoryId: 6, name: "Hope for All Clinics", description: "Mobile healthcare caravans servicing remote rural locations at zero cost.", votes: 498 },

  // 7. Musician/Artist of the Year
  { id: "nom-7-1", categoryId: 7, name: "Star Zee", description: "A trailblazing force in African dancehall and hip-hop, inspiring millions.", votes: 442 },
  { id: "nom-7-2", categoryId: 7, name: "Drizilik", description: "Grammy-recognized artist bringing Sierra Leonean 'Freetown sound' globally.", votes: 589 },
  { id: "nom-7-3", categoryId: 7, name: "Emmerson", description: "Enduring voice of musical social commentary and cultural expression.", votes: 521 },

  // 8. Legendary Award
  { id: "nom-8-1", categoryId: 8, name: "Jimmy B", description: "The Godfather of modern Sierra Leonean audio-visual and musical production.", votes: 610 },
  { id: "nom-8-2", categoryId: 8, name: "Prof. Eldred Jones", description: "Pioneering scholar who elevated African literature onto the global stage.", votes: 412 },
  { id: "nom-8-3", categoryId: 8, name: "Dr. Olayinka Koso-Thomas", description: "Pioneering medical practitioner and worldwide campaigner for women's health.", votes: 523 },

  // 9. Descendants Union of the Year
  { id: "nom-9-1", categoryId: 9, name: "Kono Descendants Union (KDU)", description: "Funded standard high school renovations and digital laboratories.", votes: 243 },
  { id: "nom-9-2", categoryId: 9, name: "Freetown Heritage Alliance", description: "Sponsoring historical preservation and disaster-relief coordination.", votes: 198 },
  { id: "nom-9-3", categoryId: 9, name: "Makeni Progressive Union", description: "Providing micro-loans to local women traders and cooperative farmers.", votes: 220 },

  // 10. International Act of the Year Award
  { id: "nom-10-1", categoryId: 10, name: "Burna Boy", description: "Grammy-winning Afrobeats star continuing to represent the continent globally.", votes: 654 },
  { id: "nom-10-2", categoryId: 10, name: "Idris Elba", description: "Global actor and advocate spearheading regional creative and smart-city investments.", votes: 789 },
  { id: "nom-10-3", categoryId: 10, name: "Wizkid", description: "Pioneering global music giant with immense cultural influence.", votes: 532 },

  // 11. Professional Award of the Year
  { id: "nom-11-1", categoryId: 11, name: "Dr. Sahr Gbakima", description: "Leading epidemiologist steering public health safety and research.", votes: 194 },
  { id: "nom-11-2", categoryId: 11, name: "Isatu Sesay", description: "Renewable energy engineer bringing solar micro-grids to rural communities.", votes: 231 },
  { id: "nom-11-3", categoryId: 11, name: "Josephine Kamara", description: "Distinguished financial executive facilitating digital banking inclusion.", votes: 180 },
];

export const COUNTRY_CODES = [
  { code: "+93", label: "🇦🇫 +93", name: "Afghanistan" },
  { code: "+355", label: "🇦🇱 +355", name: "Albania" },
  { code: "+213", label: "🇩🇿 +213", name: "Algeria" },
  { code: "+1684", label: "🇦🇸 +1684", name: "American Samoa" },
  { code: "+376", label: "🇦🇩 +376", name: "Andorra" },
  { code: "+244", label: "🇦🇴 +244", name: "Angola" },
  { code: "+1264", label: "🇦🇮 +1264", name: "Anguilla" },
  { code: "+1268", label: "🇦🇬 +1268", name: "Antigua & Barbuda" },
  { code: "+54", label: "🇦🇷 +54", name: "Argentina" },
  { code: "+374", label: "🇦🇲 +374", name: "Armenia" },
  { code: "+297", label: "🇦🇼 +297", name: "Aruba" },
  { code: "+61", label: "🇦🇺 +61", name: "Australia" },
  { code: "+43", label: "🇦🇹 +43", name: "Austria" },
  { code: "+994", label: "🇦🇿 +994", name: "Azerbaijan" },
  { code: "+1242", label: "🇧🇸 +1242", name: "Bahamas" },
  { code: "+973", label: "🇧🇭 +973", name: "Bahrain" },
  { code: "+880", label: "🇧🇩 +880", name: "Bangladesh" },
  { code: "+1246", label: "🇧🇧 +1246", name: "Barbados" },
  { code: "+375", label: "🇧🇾 +375", name: "Belarus" },
  { code: "+32", label: "🇧🇪 +32", name: "Belgium" },
  { code: "+501", label: "🇧🇿 +501", name: "Belize" },
  { code: "+229", label: "🇧🇯 +229", name: "Benin" },
  { code: "+1441", label: "🇧🇲 +1441", name: "Bermuda" },
  { code: "+975", label: "🇧🇹 +975", name: "Bhutan" },
  { code: "+591", label: "🇧🇴 +591", name: "Bolivia" },
  { code: "+387", label: "🇧🇦 +387", name: "Bosnia & Herzegovina" },
  { code: "+267", label: "🇧🇼 +267", name: "Botswana" },
  { code: "+55", label: "🇧🇷 +55", name: "Brazil" },
  { code: "+246", label: "🇮🇴 +246", name: "British Indian Ocean Territory" },
  { code: "+673", label: "🇧🇳 +673", name: "Brunei" },
  { code: "+359", label: "🇧🇬 +359", name: "Bulgaria" },
  { code: "+226", label: "🇧🇫 +226", name: "Burkina Faso" },
  { code: "+257", label: "🇧🇮 +257", name: "Burundi" },
  { code: "+855", label: "🇰🇭 +855", name: "Cambodia" },
  { code: "+237", label: "🇨🇲 +237", name: "Cameroon" },
  { code: "+1", label: "🇨🇦 +1", name: "Canada" },
  { code: "+238", label: "🇨🇻 +238", name: "Cape Verde" },
  { code: "+1345", label: "🇰🇾 +1345", name: "Cayman Islands" },
  { code: "+236", label: "🇨🇫 +236", name: "Central African Republic" },
  { code: "+235", label: "🇹🇩 +235", name: "Chad" },
  { code: "+56", label: "🇨🇱 +56", name: "Chile" },
  { code: "+86", label: "🇨🇳 +86", name: "China" },
  { code: "+57", label: "🇨🇴 +57", name: "Colombia" },
  { code: "+269", label: "🇰🇲 +269", name: "Comoros" },
  { code: "+242", label: "🇨🇬 +242", name: "Congo (Republic)" },
  { code: "+243", label: "🇨🇩 +243", name: "Congo (DR)" },
  { code: "+682", label: "🇨🇰 +682", name: "Cook Islands" },
  { code: "+506", label: "🇨🇷 +506", name: "Costa Rica" },
  { code: "+225", label: "🇨🇮 +225", name: "Côte d'Ivoire" },
  { code: "+385", label: "🇭🇷 +385", name: "Croatia" },
  { code: "+53", label: "🇨🇺 +53", name: "Cuba" },
  { code: "+357", label: "🇨🇾 +357", name: "Cyprus" },
  { code: "+420", label: "🇨🇿 +420", name: "Czech Republic" },
  { code: "+45", label: "🇩🇰 +45", name: "Denmark" },
  { code: "+253", label: "🇩🇯 +253", name: "Djibouti" },
  { code: "+1767", label: "🇩🇲 +1767", name: "Dominica" },
  { code: "+1809", label: "🇩🇴 +1809", name: "Dominican Republic" },
  { code: "+593", label: "🇪🇨 +593", name: "Ecuador" },
  { code: "+20", label: "🇪🇬 +20", name: "Egypt" },
  { code: "+503", label: "🇸🇻 +503", name: "El Salvador" },
  { code: "+240", label: "🇬🇶 +240", name: "Equatorial Guinea" },
  { code: "+291", label: "🇪🇷 +291", name: "Eritrea" },
  { code: "+372", label: "🇪🇪 +372", name: "Estonia" },
  { code: "+268", label: "🇸🇿 +268", name: "Eswatini" },
  { code: "+251", label: "🇪🇹 +251", name: "Ethiopia" },
  { code: "+500", label: "🇫🇰 +500", name: "Falkland Islands" },
  { code: "+298", label: "🇫🇴 +298", name: "Faroe Islands" },
  { code: "+679", label: "🇫🇯 +679", name: "Fiji" },
  { code: "+358", label: "🇫🇮 +358", name: "Finland" },
  { code: "+33", label: "🇫🇷 +33", name: "France" },
  { code: "+594", label: "🇬🇫 +594", name: "French Guiana" },
  { code: "+689", label: "🇵🇫 +689", name: "French Polynesia" },
  { code: "+241", label: "🇬🇦 +241", name: "Gabon" },
  { code: "+220", label: "🇬🇲 +220", name: "Gambia" },
  { code: "+995", label: "🇬🇪 +995", name: "Georgia" },
  { code: "+49", label: "🇩🇪 +49", name: "Germany" },
  { code: "+233", label: "🇬🇭 +233", name: "Ghana" },
  { code: "+350", label: "🇬🇮 +350", name: "Gibraltar" },
  { code: "+30", label: "🇬🇷 +30", name: "Greece" },
  { code: "+299", label: "🇬🇱 +299", name: "Greenland" },
  { code: "+1473", label: "🇬🇩 +1473", name: "Grenada" },
  { code: "+590", label: "🇬🇵 +590", name: "Guadeloupe" },
  { code: "+1671", label: "🇬🇺 +1671", name: "Guam" },
  { code: "+502", label: "🇬🇹 +502", name: "Guatemala" },
  { code: "+224", label: "🇬🇳 +224", name: "Guinea" },
  { code: "+245", label: "🇬🇼 +245", name: "Guinea-Bissau" },
  { code: "+592", label: "🇬🇾 +592", name: "Guyana" },
  { code: "+509", label: "🇭🇹 +509", name: "Haiti" },
  { code: "+504", label: "🇭🇳 +504", name: "Honduras" },
  { code: "+852", label: "🇭🇰 +852", name: "Hong Kong" },
  { code: "+36", label: "🇭🇺 +36", name: "Hungary" },
  { code: "+354", label: "🇮🇸 +354", name: "Iceland" },
  { code: "+91", label: "🇮🇳 +91", name: "India" },
  { code: "+62", label: "🇮🇩 +62", name: "Indonesia" },
  { code: "+98", label: "🇮🇷 +98", name: "Iran" },
  { code: "+964", label: "🇮🇶 +964", name: "Iraq" },
  { code: "+353", label: "🇮🇪 +353", name: "Ireland" },
  { code: "+972", label: "🇮🇱 +972", name: "Israel" },
  { code: "+39", label: "🇮🇹 +39", name: "Italy" },
  { code: "+1876", label: "🇯🇲 +1876", name: "Jamaica" },
  { code: "+81", label: "🇯🇵 +81", name: "Japan" },
  { code: "+962", label: "🇯🇴 +962", name: "Jordan" },
  { code: "+7", label: "🇰🇿 +7", name: "Kazakhstan" },
  { code: "+254", label: "🇰🇪 +254", name: "Kenya" },
  { code: "+686", label: "🇰🇮 +686", name: "Kiribati" },
  { code: "+850", label: "🇰🇵 +850", name: "North Korea" },
  { code: "+82", label: "🇰🇷 +82", name: "South Korea" },
  { code: "+383", label: "🇽🇰 +383", name: "Kosovo" },
  { code: "+965", label: "🇰🇼 +965", name: "Kuwait" },
  { code: "+996", label: "🇰🇬 +996", name: "Kyrgyzstan" },
  { code: "+856", label: "🇱🇦 +856", name: "Laos" },
  { code: "+371", label: "🇱🇻 +371", name: "Latvia" },
  { code: "+961", label: "🇱🇧 +961", name: "Lebanon" },
  { code: "+266", label: "🇱🇸 +266", name: "Lesotho" },
  { code: "+231", label: "🇱🇷 +231", name: "Liberia" },
  { code: "+218", label: "🇱🇾 +218", name: "Libya" },
  { code: "+423", label: "🇱🇮 +423", name: "Liechtenstein" },
  { code: "+370", label: "🇱🇹 +370", name: "Lithuania" },
  { code: "+352", label: "🇱🇺 +352", name: "Luxembourg" },
  { code: "+853", label: "🇲🇴 +853", name: "Macau" },
  { code: "+261", label: "🇲🇬 +261", name: "Madagascar" },
  { code: "+265", label: "🇲🇼 +265", name: "Malawi" },
  { code: "+60", label: "🇲🇾 +60", name: "Malaysia" },
  { code: "+960", label: "🇲🇻 +960", name: "Maldives" },
  { code: "+223", label: "🇲🇱 +223", name: "Mali" },
  { code: "+356", label: "🇲🇹 +356", name: "Malta" },
  { code: "+692", label: "🇲🇭 +692", name: "Marshall Islands" },
  { code: "+596", label: "🇲🇶 +596", name: "Martinique" },
  { code: "+222", label: "🇲🇷 +222", name: "Mauritania" },
  { code: "+230", label: "🇲🇺 +230", name: "Mauritius" },
  { code: "+262", label: "🇾🇹 +262", name: "Mayotte" },
  { code: "+52", label: "🇲🇽 +52", name: "Mexico" },
  { code: "+691", label: "🇫🇲 +691", name: "Micronesia" },
  { code: "+373", label: "🇲🇩 +373", name: "Moldova" },
  { code: "+377", label: "🇲🇨 +377", name: "Monaco" },
  { code: "+976", label: "🇲🇳 +976", name: "Mongolia" },
  { code: "+382", label: "🇲🇪 +382", name: "Montenegro" },
  { code: "+1664", label: "🇲🇸 +1664", name: "Montserrat" },
  { code: "+212", label: "🇲🇦 +212", name: "Morocco" },
  { code: "+258", label: "🇲🇿 +258", name: "Mozambique" },
  { code: "+95", label: "🇲🇲 +95", name: "Myanmar" },
  { code: "+264", label: "🇳🇦 +264", name: "Namibia" },
  { code: "+674", label: "🇳🇷 +674", name: "Nauru" },
  { code: "+977", label: "🇳🇵 +977", name: "Nepal" },
  { code: "+31", label: "🇳🇱 +31", name: "Netherlands" },
  { code: "+687", label: "🇳🇨 +687", name: "New Caledonia" },
  { code: "+64", label: "🇳🇿 +64", name: "New Zealand" },
  { code: "+505", label: "🇳🇮 +505", name: "Nicaragua" },
  { code: "+227", label: "🇳🇪 +227", name: "Niger" },
  { code: "+234", label: "🇳🇬 +234", name: "Nigeria" },
  { code: "+683", label: "🇳🇺 +683", name: "Niue" },
  { code: "+47", label: "🇳🇴 +47", name: "Norway" },
  { code: "+968", label: "🇴🇲 +968", name: "Oman" },
  { code: "+92", label: "🇵🇰 +92", name: "Pakistan" },
  { code: "+680", label: "🇵🇼 +680", name: "Palau" },
  { code: "+970", label: "🇵🇸 +970", name: "Palestine" },
  { code: "+507", label: "🇵🇦 +507", name: "Panama" },
  { code: "+675", label: "🇵🇬 +675", name: "Papua New Guinea" },
  { code: "+595", label: "🇵🇾 +595", name: "Paraguay" },
  { code: "+51", label: "🇵🇪 +51", name: "Peru" },
  { code: "+63", label: "🇵🇭 +63", name: "Philippines" },
  { code: "+48", label: "🇵🇱 +48", name: "Poland" },
  { code: "+351", label: "🇵🇹 +351", name: "Portugal" },
  { code: "+1787", label: "🇵🇷 +1787", name: "Puerto Rico" },
  { code: "+974", label: "🇶🇦 +974", name: "Qatar" },
  { code: "+40", label: "🇷🇴 +40", name: "Romania" },
  { code: "+7", label: "🇷🇺 +7", name: "Russia" },
  { code: "+250", label: "🇷🇼 +250", name: "Rwanda" },
  { code: "+290", label: "🇸🇭 +290", name: "Saint Helena" },
  { code: "+1869", label: "🇰🇳 +1869", name: "Saint Kitts & Nevis" },
  { code: "+1758", label: "🇱🇨 +1758", name: "Saint Lucia" },
  { code: "+508", label: "🇵🇲 +508", name: "Saint Pierre & Miquelon" },
  { code: "+1784", label: "🇻🇨 +1784", name: "Saint Vincent & Grenadines" },
  { code: "+685", label: "🇼🇸 +685", name: "Samoa" },
  { code: "+378", label: "🇸🇲 +378", name: "San Marino" },
  { code: "+239", label: "🇸🇹 +239", name: "Sao Tome & Principe" },
  { code: "+966", label: "🇸🇦 +966", name: "Saudi Arabia" },
  { code: "+221", label: "🇸🇳 +221", name: "Senegal" },
  { code: "+381", label: "🇷🇸 +381", name: "Serbia" },
  { code: "+248", label: "🇸🇨 +248", name: "Seychelles" },
  { code: "+232", label: "🇸🇱 +232", name: "Sierra Leone" },
  { code: "+65", label: "🇸🇬 +65", name: "Singapore" },
  { code: "+421", label: "🇸🇰 +421", name: "Slovakia" },
  { code: "+386", label: "🇸🇮 +386", name: "Slovenia" },
  { code: "+677", label: "🇸🇧 +677", name: "Solomon Islands" },
  { code: "+252", label: "🇸🇴 +252", name: "Somalia" },
  { code: "+27", label: "🇿🇦 +27", name: "South Africa" },
  { code: "+211", label: "🇸🇸 +211", name: "South Sudan" },
  { code: "+34", label: "🇪🇸 +34", name: "Spain" },
  { code: "+94", label: "🇱🇰 +94", name: "Sri Lanka" },
  { code: "+249", label: "🇸🇩 +249", name: "Sudan" },
  { code: "+597", label: "🇸🇷 +597", name: "Suriname" },
  { code: "+46", label: "🇸🇪 +46", name: "Sweden" },
  { code: "+41", label: "🇨🇭 +41", name: "Switzerland" },
  { code: "+963", label: "🇸🇾 +963", name: "Syria" },
  { code: "+886", label: "🇹🇼 +886", name: "Taiwan" },
  { code: "+992", label: "🇹🇯 +992", name: "Tajikistan" },
  { code: "+255", label: "🇹🇿 +255", name: "Tanzania" },
  { code: "+66", label: "🇹🇭 +66", name: "Thailand" },
  { code: "+670", label: "🇹🇱 +670", name: "Timor-Leste" },
  { code: "+228", label: "🇹🇬 +228", name: "Togo" },
  { code: "+690", label: "🇹🇰 +690", name: "Tokelau" },
  { code: "+676", label: "🇹🇴 +676", name: "Tonga" },
  { code: "+1868", label: "🇹🇹 +1868", name: "Trinidad & Tobago" },
  { code: "+216", label: "🇹🇳 +216", name: "Tunisia" },
  { code: "+90", label: "🇹🇷 +90", name: "Turkey" },
  { code: "+993", label: "🇹🇲 +993", name: "Turkmenistan" },
  { code: "+1649", label: "🇹🇨 +1649", name: "Turks & Caicos" },
  { code: "+688", label: "🇹🇻 +688", name: "Tuvalu" },
  { code: "+256", label: "🇺🇬 +256", name: "Uganda" },
  { code: "+380", label: "🇺🇦 +380", name: "Ukraine" },
  { code: "+971", label: "🇦🇪 +971", name: "UAE" },
  { code: "+44", label: "🇬🇧 +44", name: "United Kingdom" },
  { code: "+1", label: "🇺🇸 +1", name: "United States" },
  { code: "+598", label: "🇺🇾 +598", name: "Uruguay" },
  { code: "+998", label: "🇺🇿 +998", name: "Uzbekistan" },
  { code: "+678", label: "🇻🇺 +678", name: "Vanuatu" },
  { code: "+379", label: "🇻🇦 +379", name: "Vatican City" },
  { code: "+58", label: "🇻🇪 +58", name: "Venezuela" },
  { code: "+84", label: "🇻🇳 +84", name: "Vietnam" },
  { code: "+1284", label: "🇻🇬 +1284", name: "British Virgin Islands" },
  { code: "+1340", label: "🇻🇮 +1340", name: "US Virgin Islands" },
  { code: "+681", label: "🇼🇫 +681", name: "Wallis & Futuna" },
  { code: "+967", label: "🇾🇪 +967", name: "Yemen" },
  { code: "+260", label: "🇿🇲 +260", name: "Zambia" },
  { code: "+263", label: "🇿🇼 +263", name: "Zimbabwe" },
];
